name: ffmpeg

on:
  workflow_dispatch:
  push:
    paths:
      - ffmpeg/Dockerfile
      - .github/workflows/ffmpeg.yml

jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Hadolint
        uses: brpaz/hadolint-action@v1.5.0
        with:
          dockerfile: ffmpeg/Dockerfile

  build:
    name: Build image
    runs-on: ubuntu-latest
    needs: lint
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3.5.0
        with:
          images: ghcr.io/bratteng/toolkit/ffmpeg
          tags: |
            type=raw,value=latest

      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ffmpeg/Dockerfile
          push: ${{ github.actor != 'dependabot[bot]' }}
          load: ${{ github.actor == 'dependabot[bot]' }}
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
